
// This file contains the canonical CRM route paths for BuildHealth to validate against.
// Keep this list in sync with the <Route> definitions in src/pages/Crm.jsx.
// When a path changes in Crm.jsx, update it here.
export const expectedRoutePaths = [
  '/crm',
  '/crm/leads',
  '/crm/partners',
  '/crm/action-hub',
  '/crm/call-console',
  '/crm/pipeline-broken', // Updated as per previous request
  '/crm/estimates',
  '/crm/proposals',
  '/crm/proposals/build',
  '/crm/referrals',
  '/crm/referrals/partners',
  '/crm/inbox',
  '/crm/schedule',
  '/crm/call-log',
  '/crm/call-scripts',
  '/crm/customers',
  '/crm/marketing',
  '/crm/marketing/console',
  '/crm/marketing/funnel',
  '/crm/marketing/scoreboard',
  '/crm/reporting',
  '/crm/analytics',
  '/crm/audit-inspector',
  '/crm/automation',
  '/crm/discounts',
  '/crm/escalations',
  '/crm/pricebook-manager',
  '/crm/invoice-builder',
  '/crm/invoices',
  '/crm/service-catalog',
  '/crm/system-health',
  '/crm/system-doctor',
  '/crm/settings',
  '/crm/settings/business',
  '/crm/settings/branding',
  '/crm/settings/service-configurations',
  '/crm/settings/api-keys',
  '/crm/settings/email-templates',
  '/crm/settings/sms-templates',
  '/crm/settings/notifications',
  '/crm/settings/call-tracking',
  '/crm/settings/kanban',
  '/crm/settings/audit-log',
  '/crm/settings/rollback-manager',
  '/crm/settings/rollback-analytics',
  '/crm/settings/feedback-impact',
  '/crm/settings/system-health',
  '/crm/settings/system-diagnostics',
  '/crm/admin',
  '/crm/submissions',
  '/crm/data-tools',
  '/crm/chat-settings',
  '/crm/brand-review',
  '/crm/brand-brain'
];
