export const DOCUMENT_SYSTEM_VERSION = '2026.03.29';

export const DOCUMENT_TYPES = Object.freeze({
  ESTIMATE: 'estimate',
  QUOTE: 'quote',
  INVOICE: 'invoice',
  RECEIPT: 'receipt',
});

export const PAGE_MASTER_TYPES = Object.freeze({
  FIRST: 'first',
  INTERIOR: 'interior',
  FINAL: 'final',
});

const anyOf = (...fields) =>
  Object.freeze({
    anyOf: fields,
    label: fields.join(' or '),
  });

export const FIELD_GROUPS = Object.freeze({
  identity: Object.freeze([
    'document_type',
    'document_id',
    'document_number',
    'job_id',
    'tenant_id',
    'related_estimate_id',
    'related_quote_id',
    'related_invoice_id',
    'related_work_order_number',
    'document_version',
    'document_revision_reason',
    'source_snapshot_id',
  ]),
  commercialSummary: Object.freeze([
    'status',
    'issue_date',
    'valid_through',
    'due_date',
    'payment_terms',
    'invoice_type',
    'subtotal',
    'discount_amount',
    'tax_rate',
    'tax_amount',
    'fees_amount',
    'total_amount',
    'amount_paid',
    'balance_due',
    'payment_instructions',
    'deposit_required',
    'deposit_amount',
  ]),
  customerPropertyAp: Object.freeze([
    'customer_name',
    'company_name',
    'customer_email',
    'customer_phone',
    'property_name',
    'service_address',
    'building_name',
    'unit_reference',
    'batch_reference',
    'po_number',
    'po_required',
    'accounting_contact',
  ]),
  scopeService: Object.freeze([
    'service_summary',
    'scope_snapshot_text',
    'included_items',
    'excluded_items',
    'assumptions_text',
    'exclusions_text',
    'service_verification_text',
    'photos_available',
    'airflow_verified',
    'access_method',
    'service_date',
    'service_window',
    'line_items',
  ]),
  approvalContractControl: Object.freeze([
    'approval_required',
    'approval_method',
    'approved_by_name',
    'approved_by_email',
    'approved_at',
    'approved_version',
    'change_order_required',
    'change_order_id',
    'dispute_protection_line',
  ]),
  paymentReceipt: Object.freeze([
    'payment_reference_number',
    'payment_method',
    'payment_status',
    'payment_received_at',
    'payment_amount',
    'remaining_balance',
    'payment_provider',
    'payment_intent_id',
    'transaction_id',
    'paid_in_full',
  ]),
  deliveryAudit: Object.freeze([
    'public_token',
    'sent_at',
    'viewed_at',
    'delivery_channel',
    'last_delivery_status',
    'created_by',
    'updated_by',
    'released_for_send',
  ]),
  internalControl: Object.freeze([
    'template_version',
    'render_profile',
    'generated_by',
    'release_checked_by',
    'document_freeze_at',
    'snapshot_hash',
    'snapshot_storage_mode',
  ]),
});

export const DOCUMENT_FIELD_REQUIREMENTS = Object.freeze({
  estimate: Object.freeze({
    required: Object.freeze([
      'document_type',
      'document_id',
      'document_number',
      anyOf('job_id', 'draft_job_identity'),
      'status',
      'customer_name',
      'service_address',
      'service_summary',
      'scope_snapshot_text',
      'assumptions_text',
      'subtotal',
      'total_amount',
      'valid_through',
    ]),
    optional: Object.freeze([
      'unit_reference',
      'batch_reference',
      'service_window',
      'photos_available',
      'line_items',
    ]),
  }),
  quote: Object.freeze({
    required: Object.freeze([
      'document_type',
      'document_id',
      'document_number',
      'quote_number',
      'job_id',
      'status',
      'customer_name',
      'service_address',
      'service_summary',
      'scope_snapshot_text',
      'assumptions_text',
      'subtotal',
      'total_amount',
      'valid_through',
      'approved_version',
      'dispute_protection_line',
      'included_items',
      'excluded_items',
      'approval_required',
      'approval_method',
      'payment_terms',
    ]),
    optional: Object.freeze([
      'deposit_required',
      'deposit_amount',
      'po_required',
      'po_number',
      'line_items',
      'batch_reference',
      'unit_reference',
    ]),
  }),
  invoice: Object.freeze({
    required: Object.freeze([
      'document_type',
      'document_id',
      'document_number',
      'invoice_number',
      'job_id',
      'related_quote_id',
      'status',
      'issue_date',
      'due_date',
      'customer_name',
      'service_address',
      'service_date',
      'payment_terms',
      'line_items',
      'subtotal',
      'tax_amount',
      'total_amount',
      'amount_paid',
      'balance_due',
      'payment_instructions',
      'dispute_protection_line',
      'service_verification_text',
    ]),
    optional: Object.freeze([
      'po_number',
      'unit_reference',
      'batch_reference',
      'airflow_verified',
      'photos_available',
    ]),
  }),
  receipt: Object.freeze({
    required: Object.freeze([
      'document_type',
      'document_id',
      'document_number',
      'invoice_number',
      'job_id',
      'status',
      'customer_name',
      'service_address',
      'payment_amount',
      'payment_method',
      'payment_received_at',
      'payment_reference_number',
      anyOf('paid_in_full', 'remaining_balance'),
    ]),
    optional: Object.freeze([
      'transaction_id',
      'payment_provider',
      'review_url',
      'related_invoice_id',
    ]),
  }),
});

export const SECTION_DEFINITIONS = Object.freeze({
  scan_first: Object.freeze({ atomic: true, splittable: false, major: true, denseTable: false }),
  client_property: Object.freeze({ atomic: true, splittable: false, major: true, denseTable: false }),
  scope_snapshot: Object.freeze({ atomic: true, splittable: false, major: true, denseTable: false }),
  pricing_table: Object.freeze({
    atomic: false,
    splittable: true,
    major: true,
    denseTable: true,
    continuedLabel: 'Pricing (continued)',
  }),
  included_excluded: Object.freeze({ atomic: true, splittable: false, major: false, denseTable: false }),
  validity_window: Object.freeze({ atomic: true, splittable: false, major: false, denseTable: false }),
  assumptions: Object.freeze({ atomic: false, splittable: true, major: false, denseTable: false }),
  exclusions: Object.freeze({ atomic: false, splittable: true, major: false, denseTable: false }),
  add_ons: Object.freeze({ atomic: false, splittable: true, major: false, denseTable: false }),
  service_notes: Object.freeze({ atomic: false, splittable: true, major: false, denseTable: false }),
  unit_schedule: Object.freeze({ atomic: false, splittable: true, major: true, denseTable: true }),
  service_summary: Object.freeze({ atomic: true, splittable: false, major: false, denseTable: false }),
  totals: Object.freeze({ atomic: true, splittable: false, major: true, denseTable: false }),
  payment_terms: Object.freeze({ atomic: true, splittable: false, major: false, denseTable: false }),
  approval: Object.freeze({ atomic: true, splittable: false, major: true, denseTable: false }),
  dispute_protection: Object.freeze({ atomic: true, splittable: false, major: false, denseTable: false }),
  service_verification: Object.freeze({ atomic: true, splittable: false, major: false, denseTable: false }),
  payment_confirmation: Object.freeze({ atomic: true, splittable: false, major: true, denseTable: false }),
  remit_to: Object.freeze({ atomic: true, splittable: false, major: false, denseTable: false }),
  next_steps: Object.freeze({ atomic: true, splittable: false, major: false, denseTable: false }),
});

export const PAGE_MASTER_RULES = Object.freeze({
  first: Object.freeze({
    purpose: 'establish trust, identify the document, and surface price and scope quickly',
    allowedSections: Object.freeze([
      'scan_first',
      'client_property',
      'scope_snapshot',
      'pricing_table',
      'included_excluded',
      'validity_window',
      'service_summary',
      'next_steps',
    ]),
    disallowedSections: Object.freeze([
      'approval',
      'assumptions',
      'exclusions',
      'add_ons',
      'unit_schedule',
    ]),
    allowFinalSectionsOnSinglePage: true,
    headerFields: Object.freeze(['horizontal_logo', 'document_type', 'scan_first']),
    footerFields: Object.freeze(['company_contact', 'compact_badge_row', 'page_number']),
  }),
  interior: Object.freeze({
    purpose: 'continuation only',
    allowedSections: Object.freeze([
      'pricing_table',
      'assumptions',
      'exclusions',
      'add_ons',
      'service_notes',
      'unit_schedule',
      'included_excluded',
      'validity_window',
      'service_verification',
    ]),
    disallowedSections: Object.freeze([
      'approval',
      'scan_first',
      'next_steps',
      'payment_confirmation',
    ]),
    headerFields: Object.freeze(['compact_logo', 'document_type', 'document_number', 'job_id', 'property', 'page_number']),
    footerFields: Object.freeze(['company_contact', 'compact_badge_row', 'page_number']),
  }),
  final: Object.freeze({
    purpose: 'financial closure and action',
    allowedSections: Object.freeze([
      'included_excluded',
      'validity_window',
      'assumptions',
      'exclusions',
      'service_notes',
      'service_summary',
      'service_verification',
      'payment_confirmation',
      'remit_to',
      'totals',
      'payment_terms',
      'approval',
      'dispute_protection',
    ]),
    requiredTailOrder: Object.freeze([
      'totals',
      'payment_terms',
      'approval',
      'dispute_protection',
    ]),
    headerFields: Object.freeze(['compact_logo', 'document_type', 'document_number', 'job_id', 'property', 'page_number']),
    footerFields: Object.freeze(['company_contact', 'compact_badge_row', 'page_number']),
  }),
});

export const DOCUMENT_CONTENT_RULES = Object.freeze({
  estimate: Object.freeze({
    scanFirstRequired: false,
    requiredSections: Object.freeze([
      'client_property',
      'scope_snapshot',
      'assumptions',
      'exclusions',
      'pricing_table',
      'next_steps',
    ]),
    prohibitedSections: Object.freeze(['approval']),
  }),
  quote: Object.freeze({
    scanFirstRequired: true,
    requiredSections: Object.freeze([
      'scan_first',
      'scope_snapshot',
      'included_excluded',
      'pricing_table',
      'validity_window',
      'approval',
      'dispute_protection',
    ]),
    prohibitedSections: Object.freeze([]),
  }),
  invoice: Object.freeze({
    scanFirstRequired: true,
    requiredSections: Object.freeze([
      'scan_first',
      'client_property',
      'service_summary',
      'pricing_table',
      'totals',
      'payment_terms',
      'service_verification',
      'dispute_protection',
    ]),
    prohibitedSections: Object.freeze(['add_ons']),
  }),
  receipt: Object.freeze({
    scanFirstRequired: true,
    requiredSections: Object.freeze([
      'scan_first',
      'payment_confirmation',
    ]),
    prohibitedSections: Object.freeze(['approval', 'add_ons', 'pricing_table']),
  }),
});

export const DISPLAY_LABELS = Object.freeze({
  shared: Object.freeze({
    document_number: 'Document #',
    job_id: 'Job ID',
    property_name: 'Property',
    service_address: 'Service Address',
    status: 'Status',
    customer_name: 'Customer',
    po_number: 'PO Number',
    payment_terms: 'Payment Terms',
    payment_instructions: 'Payment Instructions',
    service_verification_text: 'Service Verification',
    dispute_protection_line: 'Scope Protection',
  }),
  estimate: Object.freeze({
    total_amount: 'Estimated Total',
    valid_through: 'Estimate Expires',
    service_summary: 'Estimated Scope',
    next_steps: 'Next Step',
  }),
  quote: Object.freeze({
    total_amount: 'Total Investment',
    valid_through: 'Valid Through',
    approval: 'Approve to Schedule Service',
    service_summary: 'Committed Scope',
  }),
  invoice: Object.freeze({
    total_amount: 'Total Invoice',
    amount_paid: 'Payments Applied',
    balance_due: 'Balance Due',
    due_date: 'Due Date',
    payment_instructions: 'How to Pay',
  }),
  receipt: Object.freeze({
    payment_amount: 'Amount Paid',
    payment_received_at: 'Date Paid',
    remaining_balance: 'Remaining Balance',
    paid_in_full: 'Paid in Full',
    payment_reference_number: 'Receipt Reference',
  }),
});

export const REQUIRED_PROTECTION_LINES = Object.freeze({
  dispute: 'All services, scope, and pricing are tied to the approved quote version referenced in this document.',
  serviceVerification: 'Service documented with pre/post photos and airflow verification.',
});

export const RELEASE_CHECKLISTS = Object.freeze({
  estimate: Object.freeze([
    Object.freeze({ id: 'required_fields', label: 'Required fields present' }),
    Object.freeze({ id: 'totals_reconcile', label: 'Totals reconcile' }),
    Object.freeze({ id: 'null_render_pass_clean', label: 'Null rendering pass clean' }),
  ]),
  quote: Object.freeze([
    Object.freeze({ id: 'required_fields', label: 'Required fields present' }),
    Object.freeze({ id: 'document_version_assigned', label: 'Document version assigned' }),
    Object.freeze({ id: 'scope_snapshot_present', label: 'Scope snapshot present' }),
    Object.freeze({ id: 'totals_reconcile', label: 'Totals reconcile' }),
    Object.freeze({ id: 'page_count_stable', label: 'Page count stable' }),
    Object.freeze({ id: 'approval_placement_correct', label: 'Approval placement correct' }),
    Object.freeze({ id: 'po_resolved_if_applicable', label: 'PO field resolved if applicable' }),
    Object.freeze({ id: 'dispute_line_present', label: 'Dispute line present' }),
    Object.freeze({ id: 'null_render_pass_clean', label: 'Null rendering pass clean' }),
  ]),
  invoice: Object.freeze([
    Object.freeze({ id: 'required_fields', label: 'Required fields present' }),
    Object.freeze({ id: 'totals_reconcile', label: 'Totals reconcile' }),
    Object.freeze({ id: 'service_date_present', label: 'Service date present' }),
    Object.freeze({ id: 'balance_due_correct', label: 'Balance due correct' }),
    Object.freeze({ id: 'payment_instructions_present', label: 'Payment instructions present' }),
    Object.freeze({ id: 'dispute_line_present', label: 'Dispute line present' }),
    Object.freeze({ id: 'service_verification_present', label: 'Service verification line present' }),
    Object.freeze({ id: 'release_approval_present', label: 'Release approval present when sending' }),
    Object.freeze({ id: 'null_render_pass_clean', label: 'Null rendering pass clean' }),
  ]),
  receipt: Object.freeze([
    Object.freeze({ id: 'payment_event_confirmed', label: 'Invoice paid state or payment event confirmed' }),
    Object.freeze({ id: 'payment_amount_matches', label: 'Payment amount matches selected transaction payload' }),
    Object.freeze({ id: 'payment_method_present', label: 'Payment method present' }),
    Object.freeze({ id: 'payment_timestamp_present', label: 'Payment timestamp present' }),
    Object.freeze({ id: 'balance_outcome_clear', label: 'Balance outcome is clear' }),
  ]),
});

export const DOCUMENT_STATE_RULES = Object.freeze({
  estimate: Object.freeze({
    statuses: Object.freeze(['draft', 'sent', 'viewed', 'expired', 'converted', 'void']),
    transitions: Object.freeze({
      draft: Object.freeze(['sent', 'void']),
      sent: Object.freeze(['viewed', 'expired', 'converted', 'void']),
      viewed: Object.freeze(['expired', 'converted', 'void']),
      expired: Object.freeze(['void']),
      converted: Object.freeze([]),
      void: Object.freeze([]),
    }),
  }),
  quote: Object.freeze({
    statuses: Object.freeze(['draft', 'pending_review', 'sent', 'viewed', 'approved', 'declined', 'expired', 'superseded', 'void']),
    transitions: Object.freeze({
      draft: Object.freeze(['pending_review', 'sent', 'void']),
      pending_review: Object.freeze(['draft', 'sent', 'void']),
      sent: Object.freeze(['viewed', 'approved', 'declined', 'expired', 'superseded', 'void']),
      viewed: Object.freeze(['approved', 'declined', 'expired', 'superseded', 'void']),
      approved: Object.freeze(['superseded']),
      declined: Object.freeze(['superseded']),
      expired: Object.freeze(['superseded', 'void']),
      superseded: Object.freeze([]),
      void: Object.freeze([]),
    }),
  }),
  invoice: Object.freeze({
    statuses: Object.freeze(['draft', 'sent', 'partial', 'paid', 'overdue', 'void']),
    transitions: Object.freeze({
      draft: Object.freeze(['sent', 'void']),
      sent: Object.freeze(['partial', 'paid', 'overdue', 'void']),
      partial: Object.freeze(['paid', 'overdue', 'void']),
      overdue: Object.freeze(['partial', 'paid', 'void']),
      paid: Object.freeze([]),
      void: Object.freeze([]),
    }),
  }),
  receipt: Object.freeze({
    statuses: Object.freeze(['pending', 'sent', 'sent_sms', 'skipped', 'suppressed', 'failed']),
    transitions: Object.freeze({
      pending: Object.freeze(['sent', 'sent_sms', 'skipped', 'suppressed', 'failed']),
      failed: Object.freeze(['sent', 'sent_sms', 'skipped', 'suppressed']),
      sent: Object.freeze([]),
      sent_sms: Object.freeze([]),
      skipped: Object.freeze([]),
      suppressed: Object.freeze([]),
    }),
  }),
});

export const TRANSFORMATION_RULES = Object.freeze({
  estimate_to_quote: Object.freeze({
    allowedEdits: Object.freeze(['scope_snapshot_text', 'line_items', 'subtotal', 'tax_amount', 'total_amount', 'assumptions_text']),
    requiredResolution: Object.freeze(['assumptions_text']),
  }),
  quote_to_approved_snapshot: Object.freeze({
    locks: Object.freeze([
      'scope_snapshot_text',
      'line_items',
      'subtotal',
      'tax_amount',
      'total_amount',
      'unit_reference',
      'batch_reference',
      'payment_terms',
      'document_version',
    ]),
    requiredFields: Object.freeze(['approved_version', 'source_snapshot_id']),
  }),
  quote_to_invoice: Object.freeze({
    lockedFields: Object.freeze([
      'scope_snapshot_text',
      'line_items',
      'subtotal',
      'tax_amount',
      'total_amount',
      'unit_reference',
      'batch_reference',
      'access_method',
    ]),
    allowedWithoutChangeOrder: Object.freeze([
      'amount_paid',
      'balance_due',
      'payment_status',
      'release_approved',
    ]),
    changeOrderRequiredFor: Object.freeze([
      'scope_snapshot_text',
      'access_method',
      'quantity',
      'unit_reference',
      'batch_reference',
      'materials',
      'price',
      'line_items',
      'included_items',
      'excluded_items',
    ]),
  }),
  invoice_correction: Object.freeze({
    allowedActions: Object.freeze(['revised_document', 'credit_memo', 'void']),
    prohibitedActions: Object.freeze(['silent_edit']),
  }),
});

export const DOCUMENT_SYSTEM_CONFIG = Object.freeze({
  version: DOCUMENT_SYSTEM_VERSION,
  documentTypes: DOCUMENT_TYPES,
  pageMasters: PAGE_MASTER_TYPES,
  fieldGroups: FIELD_GROUPS,
  documentFieldRequirements: DOCUMENT_FIELD_REQUIREMENTS,
  sectionDefinitions: SECTION_DEFINITIONS,
  pageMasterRules: PAGE_MASTER_RULES,
  documentContentRules: DOCUMENT_CONTENT_RULES,
  displayLabels: DISPLAY_LABELS,
  requiredProtectionLines: REQUIRED_PROTECTION_LINES,
  releaseChecklists: RELEASE_CHECKLISTS,
  documentStateRules: DOCUMENT_STATE_RULES,
  transformationRules: TRANSFORMATION_RULES,
});
